version: "3.8"

services:
  db:
    image: postgres:10.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - bridge-network

  webpacker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec bin/webpack-dev-server
    working_dir: /var/www/html
    environment:
      RAILS_ENV:     "development"
      PSQL_PASSWORD: "postgrespwd"
      PSQL_USERNAME: "postgres"
      PSQL_HOST:     "db"
      PSQL_PORT:     "5432"
      PORT:          "3000"
    volumes:
      - .:/var/www/html
      - modules_cache:/var/www/html/node_modules
      - bundle_cache:/bundle
    ports:
      - "3035:3035"
    depends_on:
      - db
    networks:
      - bridge-network

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh serve.sh
    working_dir: /var/www/html
    environment:
      RAILS_ENV:     "development"
      PSQL_PASSWORD: "postgrespwd"
      PSQL_USERNAME: "postgres"
      PSQL_HOST:     "db"
      PSQL_PORT:     "5432"
      PORT:          "3000"
    volumes:
      - .:/var/www/html
      - modules_cache:/var/www/html/node_modules
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
    networks:
      - bridge-network

volumes:
  pgdata:
  modules_cache:
  bundle_cache:

networks:
  bridge-network: